words = [
    "ADQ",
    "Deque",
    "SEARCHEXAMPLE",
    "Sedgewick",
    "abbcdefghijkllmnopqrst",
    "bms",
    "bst",
    "dequeue'ing",
    "enqueue'ing",
    "growable",
    "qetaljrcipbmnhgfdlbsok",
    "sls",
    "tsrqponmllkjihgfedcbba",
]
